# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92e650003aa474f243316614412f60969836b3f91d6a96c387f9538547433f21aa6f27ecb57e066bc041451b36e54dfb35edaf03f60c1b4b6c1bdb3f51311312

test:
  secret_key_base: 4858d79254cf95112ab06a4a6c67f0c2aaf27fd86eb91ddb647be269d830061fadf1fc43521d35b3ab55836b5df23a163c901e327581f9e84213f2ddc2be256f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
